[tools]
node = "lts"
pnpm = "10"

[env]
_.path = ['./node_modules/.bin']

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'
